########################################################################################################################
path:
  'output': '/home/olga/ABC_MCMC/output/'
  'valid_data': '/home/olga/ABC_MCMC/rans_ode/valid_data/'     # truth data
########################################################################################################################
case: 'impulsive'                 # options: 'impulsive', 'periodic', 'decay', 'strain-relax'
########################################################################################################################
abc_algorithm: 'abc'       # options: 'abc', 'abc_IMCMC', 'abc_MCMC_adaptive'
#################################################################################################################
## Define only one of the following
#################################################################################################################
algorithm:
  abc:
      sampling: 'uniform'     # 'uniform', 'random', 'sobol'
      N: 10000                # per dimension
  ############################################################################################################
  abc_IMCMC:
      # Calibration
      sampling: 'uniform'     # 'uniform', 'random', 'sobol'
      N_calibration:
        - 6                  # recommended 10
        - 6                  # recommended 10
      x:
        - 0.1                  # percent of accepted for calibration step 1
        - 0.1                  # percent of accepted for calibration step 2
      phi: 1
      prior_update: 10          # 0 or Number of bins per dimension (to update the prior based on calibration posterior)
      # MCMC
      N_per_chain: 500
      t0: 100                  # burn-in period without kernel adaptation
  ############################################################################################################
  abc_MCMC_adaptive:
      t0: 50
      target_acceptance: 0.5
      N_per_chain: 100
  ############################################################################################################
########################################################################################################################
C_limits:
  - [1.2, 2.2]
#  - [0.6, 0.8]
#  - [1.6, 2]
#  - [1.75, 2.05]
C_nominal:
#  - 1.5
#  - 0.8
#  - 1.44
#  - 1.92
  - 1.4
  - 0.71
  - 1.854
  - 1.912
########################################################################################################################
parallel_threads: 4          # Number of processes
########################################################################################################################
#
